<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <RootNamespace>louis_agent.orchestrator</RootNamespace>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <InternalsVisibleTo Include="louis-agent.orchestrator.tests" />
      <ProjectReference Include="..\..\louis-agent.core\louis-agent.core.csproj" />
    </ItemGroup>

    <ItemGroup>
      <None Include="Skills\**\*.md" CopyToOutputDirectory="PreserveNewest" />
    </ItemGroup>

</Project>
